### ISSUE TITLE
Demo please?

### ISSUE THREAD

**Issue by estaub** [spion/typescript-workspace-plugin#2]
I can't get this to work.  It would be far easier to figure out what's wrong if there was a working example monorepo!

**Comment by spion** [comment]
Is that VSCode? There cannot be a working example due to the security restriction it has.

But I could add the following to the readme:

Once you install and configure the plugin, in cmd+shift+p (ctrl+shift+p):

* typescript version
* "use workspace version"

This will ensure that the plugin actually loads - otherwise it wont. If it still doesn't work after that, a `cmd+shift+p -> Reload` afterwards might help.

**Comment by estaub** [comment]
No, I'm just trying to get it to work outside of any IDE, from command-line invocation of tsc.

**Comment by spion** [comment]
This plugin is specifically meant to work in an IDE with tsserver.

**Comment by spion** [comment]
You might want to check out wsrun which is a workspace command runner: https://github.com/whoeverest/wsrun
